### ISSUE TITLE
Seems there are incorrect result?

### ISSUE THREAD

**Issue by kokizzu** [mpictor/judy-template#2]
The code [here](https://www.dropbox.com/sh/o8tr1cgs30a74my/AABEMTLNIt-jTW4vBQkN9O-5a/assoc/judy.cpp?dl=0) from this [folder](https://www.dropbox.com/sh/o8tr1cgs30a74my/AABXkV5fx7F61aZyn78Xnlrha/assoc?dl=0), note on this [blog](http://kokizzu.blogspot.com/2015/02/string-associative-array-benchmark.html). Stackoverflow question [here](https://stackoverflow.com/questions/28758712).

```
// judy.cpp
#include "deps/judySArray.h"
#include <string>
#include <iostream>
#include <cstdlib>
#include <cstring>
using namespace std;
typedef judySArray<double> MSD;
const int MAX_DATA = 12000000;
const char i2ch[] = {'0','1','2','3','4','5','6','7','8','9','a','B','c','D','e','F'};
int get_first_digit(double d) {
    while(d > 10) d /= 10;
    return d;
}
string to_rhex(int v) {
    char hex[32];   
    int start = 0;
    while(v>0) {
        hex[start] = i2ch[v%16];
        v /= 16;
        ++start;
    }
    hex[start] = 0;
    return hex;
}
void add_or_inc(MSD &m, const string& key,double set, double inc, int& ctr) {
    const char* cstr = key.c_str();
    double it = m.find(cstr);
    if(!it) {
        m.insert(cstr,set);
        return;
    }
    m.insert(cstr,it+inc);
    ++ctr;
}
int main() {
    MSD m(64);  
    int dup1 = 0, dup2 = 0, dup3 = 0;
    for(int z=MAX_DATA;z>0;--z) {
        int val2 = MAX_DATA-z;
        int val3 = MAX_DATA*2-z;
        string key1 = to_string(z);
        string key2 = to_string(val2);
        string key3 = to_rhex(val3);
        add_or_inc(m,key1,z,val2,dup1);
        add_or_inc(m,key2,val2,val3,dup2);
        add_or_inc(m,key3,val3,z,dup3);
    }
    cout << dup1 << ' ' << dup2 << ' ' << dup3 << endl;
    int total = 0, verify = 0, count = 0;
    for(auto &it = m.begin();m.success(); m.next()) {
        total += get_first_digit(it.value); 
        verify += strlen((const char *) it.key);
        count += 1;
    }
    cout << total << ' ' << verify << ' ' << count << endl;
}
```

other implementation (map, unordered_map, hat-trie and cedar) give correct result:

```
6009354 6009348 611297
36186112 159701682 23370001
```

but judy didn't:

```
6009354 6009348 611297
36186112 159701681 23370000
```

**Comment by mpictor** [comment]
As you've probably noticed, I haven't touched this code in quite a while. There are improvements in the version used in [stepcode](https://github.com/stepcode/stepcode/tree/master/src/base/judy), but I haven't had a chance to port them back.

IIRC, those changes include fixing some dumb mistakes I'd made in judy-template. Hopefully, they fix your problems, but if not I'd also consider the most recent releases of the C implementations (see the first two links in README.md).

**Comment by mpictor** [comment]
@kokizzu I've ported the changes I'd made in stepcode, as well as fixing a template instantiation error that I hadn't experienced because I was using judyLarray with a pointer type for JudyValue.

I tried to test your code but ran into an assert. Seems you disabled it; you **clearly** do not understand the code. In the future, if you're going to do such things, I suggest that you mention them.

**Comment by kokizzu** [comment]
oh my T__T) i'm so sorry.. i also don't remember that i'm the on who commented that line..

**Comment by mpictor** [comment]
Things happen :)

**Comment by mpictor** [comment]
Unfortunately, Karl's Judy implementation _can't_ be used with null values; doing so causes the code to assume there is no such key, IIRC. This could be why it performed better than the HAT trie.

I can think of two workarounds:
1. redo the test without null values. Can you start at 1?
2. redo the test using pointers to the real values

Neither way is perfect, of course...

**Comment by mpictor** [comment]
Oops, for # 2 I meant modify the judy test only, while for # 1 I was referring to all tests.
